global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'weops.uac.hook'

receivers:
- name: 'weops.uac.hook'
  webhook_configs:
  - url: "${webhook_url}"